[build-system]
requires = ["scikit-build-core>=0.10", "nanobind>=1.9.2"]
build-backend = "scikit_build_core.build"

[project]
name = "bionify"
version = "0.1.3"
description = "A high-performance bionic reading traceback and log formatter for the terminal."
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
  { name = "Pranay", email = "b.pranay.git@gmail.com" }
]
dependencies = [
  "colorama>=0.4.6"
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: C++",
  "Operating System :: Microsoft :: Windows",
  "Topic :: Software Development :: Debuggers",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License"
]

[project.urls]
Homepage = "https://github.com/Pranay-Bhaskar/bionify"
Repository = "https://github.com/Pranay-Bhaskar/bionify.git"
"Bug Tracker" = "https://github.com/Pranay-Bhaskar/bionify/issues"

[tool.scikit-build]
minimum-version = "0.10"
build-dir = "build/{wheel_tag}"
wheel.packages = ["src/bionify"]

[tool.scikit-build.cmake.define]
CMAKE_CXX_STANDARD = "17"
CMAKE_CXX_STANDARD_REQUIRED = "ON"